version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: gotouchgrass-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: gotouchgrass-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-atlas-data:/data/db
      - mongo-atlas-config:/data/configdb
      - mongo-atlas-search:/data/mongot
    restart: always

  redis:
    image: redis:alpine
    container_name: gotouchgrass-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: gotouchgrass-mongo-express
    ports:
      - "8081:8081"
    environment:  
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER:-mongodb}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: gotouchgrass-prometheus
    restart: always
    volumes:
      - ./../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: gotouchgrass-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./../grafana/provisioning:/etc/grafana/provisioning
      - ./../grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  mongo-atlas-data:
  mongo-atlas-config:
  mongo-atlas-search:
